version: '0'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: backend
    container_name: backend
    ports:
      - '8080:8080'
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: frontend
    container_name: frontend
    ports:
      - '8501:8501'
    depends_on:
      - backend
