FROM python:3.10-slim

WORKDIR /app

COPY src/ /app/src
COPY data/ /app/data

COPY requirements_backend.txt /app

RUN pip install --upgrade pip && pip install -r requirements_backend.txt

WORKDIR /app/src

CMD ["uvicorn", "main:app",  "--reload", "--host", "0.0.0.0", "--port", "8080"] 