FROM python:3.10-slim

WORKDIR /app

COPY src/ /app/src
COPY data/ /app/data

COPY requirements_main.txt /app

RUN pip install --upgrade pip && pip install -r requirements_main.txt

WORKDIR /app/src

EXPOSE 8080

CMD ["uvicorn", "main:app",  "--reload", "--port=8080"] 