FROM python:3.10-slim

WORKDIR /app

COPY src/app.py /app

COPY requirements_frontend.txt /app

RUN  pip install --upgrade pip && pip install -r requirements_frontend.txt

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.enableCORS", "false", "--server.enableXsrfProtection", "false"]
